default:
  before_script:
    - apt update
    - apt install -y ansible
    - ansible --version
    - ansible localhost -m setup
    - cd ansible
    - echo localhost ansible_connection=local > inventory
    - ansible-playbook $CI_ANSIBLE_PLAYBOOK_EXTRA_ARGS example-playbook.yml

example Playbook on Buster:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - buster

example Playbook on Bullseye:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - bullseye
