default:
  before_script:
    - apt update
    - apt install -y ansible
    - ansible --version > ansible-version.txt
    - ansible localhost -m setup > facts.txt
    - cd ansible
      && ansible-playbook $CI_ANSIBLE_PLAYBOOK_EXTRA_ARGS .ci-playbook.yml

  artifacts:
    untracked: true
    when: always
    expire_in: 3 months

patch on buster:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - buster

patch on bullseye:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - bullseye
