default:
  before_script:
    - apt update
    - apt install -y ansible
    - ansible --version
    - ansible localhost -m setup
    - cd ansible

    # setting ``ansible_python_interpreter`` is a temporary fix,
    # since it is apparently detected wrongly on Buster in combination
    # with ``connection=local``:
    # https://gitlab.com/hpi-potsdam/osm/g5-on-linux/11p-on-linux/-/jobs/1698419117
    - echo localhost ansible_connection=local
                     ansible_python_interpreter=/usr/bin/python3
      > inventory

    - ansible-playbook $CI_ANSIBLE_PLAYBOOK_EXTRA_ARGS example-playbook.yml

example Playbook on Buster:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - buster

example Playbook on Bullseye:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - bullseye

example Playbook on Focal:
  script: echo script cannot be blank :\)
  tags:
    - kvm
    - focal
